export type Frame = {
  id: string;
  name: string;
  brand: string;
  shape: "Round" | "Square" | "Rectangle" | "Cat-Eye" | "Aviator";
  color: string;
  width: number; // total frame width in mm (S 128 / M 138 / L 148)
  size: "S" | "M" | "L";
  price: number;
  emoji: string;
};

export const FRAMES: Frame[] = [
  {
    id: "f1",
    name: "Aurora",
    brand: "Gowri Signature",
    shape: "Round",
    color: "Tortoise",
    width: 138,
    size: "M",
    price: 2499,
    emoji: "👓",
  },
  {
    id: "f2",
    name: "Meridian",
    brand: "Gowri Edge",
    shape: "Square",
    color: "Matte Black",
    width: 142,
    size: "M",
    price: 2999,
    emoji: "🕶️",
  },
  {
    id: "f3",
    name: "Coral",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Rose Gold",
    width: 134,
    size: "S",
    price: 3499,
    emoji: "👓",
  },
  {
    id: "f4",
    name: "Sky Pilot",
    brand: "Gowri Air",
    shape: "Aviator",
    color: "Gunmetal",
    width: 146,
    size: "L",
    price: 3299,
    emoji: "🕶️",
  },
  {
    id: "f5",
    name: "Studio",
    brand: "Gowri Signature",
    shape: "Rectangle",
    color: "Crystal Clear",
    width: 140,
    size: "M",
    price: 1999,
    emoji: "👓",
  },
  {
    id: "f6",
    name: "Lumen",
    brand: "Gowri Edge",
    shape: "Round",
    color: "Brushed Silver",
    width: 130,
    size: "S",
    price: 2799,
    emoji: "👓",
  },
  {
    id: "f7",
    name: "Atlas",
    brand: "Gowri Air",
    shape: "Square",
    color: "Forest Green",
    width: 148,
    size: "L",
    price: 3199,
    emoji: "🕶️",
  },
  {
    id: "f8",
    name: "Petal",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Burgundy",
    width: 136,
    size: "M",
    price: 2899,
    emoji: "👓",
  },
  {
    id: "f9",
    name: "North",
    brand: "Gowri Signature",
    shape: "Rectangle",
    color: "Deep Navy",
    width: 144,
    size: "L",
    price: 2599,
    emoji: "👓",
  },
  {
    id: "f10",
    name: "Halo",
    brand: "Gowri Bloom",
    shape: "Round",
    color: "Blush Pink",
    width: 132,
    size: "S",
    price: 2699,
    emoji: "👓",
  },
  {
    id: "f11",
    name: "Forge",
    brand: "Gowri Edge",
    shape: "Rectangle",
    color: "Charcoal",
    width: 145,
    size: "L",
    price: 2399,
    emoji: "👓",
  },
  {
    id: "f12",
    name: "Mirage",
    brand: "Gowri Air",
    shape: "Aviator",
    color: "Champagne Gold",
    width: 144,
    size: "L",
    price: 3599,
    emoji: "🕶️",
  },
  {
    id: "f13",
    name: "Iris",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Lavender",
    width: 135,
    size: "M",
    price: 3099,
    emoji: "👓",
  },
  {
    id: "f14",
    name: "Quill",
    brand: "Gowri Signature",
    shape: "Round",
    color: "Honey Tortoise",
    width: 140,
    size: "M",
    price: 2799,
    emoji: "👓",
  },
  {
    id: "f15",
    name: "Vertex",
    brand: "Gowri Edge",
    shape: "Square",
    color: "Jet Black",
    width: 138,
    size: "M",
    price: 2499,
    emoji: "👓",
  },
  {
    id: "f16",
    name: "Beacon",
    brand: "Gowri Air",
    shape: "Aviator",
    color: "Silver Mirror",
    width: 147,
    size: "L",
    price: 3799,
    emoji: "🕶️",
  },
  {
    id: "f17",
    name: "Ember",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Amber",
    width: 134,
    size: "S",
    price: 2999,
    emoji: "👓",
  },
  {
    id: "f18",
    name: "Glide",
    brand: "Gowri Edge",
    shape: "Rectangle",
    color: "Slate",
    width: 143,
    size: "M",
    price: 2299,
    emoji: "👓",
  },
  {
    id: "f19",
    name: "Tide",
    brand: "Gowri Signature",
    shape: "Round",
    color: "Ocean Blue",
    width: 136,
    size: "M",
    price: 2699,
    emoji: "👓",
  },
  {
    id: "f20",
    name: "Pivot",
    brand: "Gowri Edge",
    shape: "Square",
    color: "Olive",
    width: 141,
    size: "M",
    price: 2599,
    emoji: "👓",
  },
  {
    id: "f21",
    name: "Lyric",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Coral",
    width: 133,
    size: "S",
    price: 3199,
    emoji: "👓",
  },
  {
    id: "f22",
    name: "Echo",
    brand: "Gowri Signature",
    shape: "Round",
    color: "Smoke Grey",
    width: 142,
    size: "M",
    price: 2899,
    emoji: "👓",
  },
  {
    id: "f23",
    name: "Ridge",
    brand: "Gowri Air",
    shape: "Aviator",
    color: "Bronze",
    width: 149,
    size: "L",
    price: 3499,
    emoji: "🕶️",
  },
  {
    id: "f24",
    name: "Frost",
    brand: "Gowri Edge",
    shape: "Rectangle",
    color: "Ice White",
    width: 139,
    size: "M",
    price: 2199,
    emoji: "👓",
  },
  {
    id: "f25",
    name: "Saga",
    brand: "Gowri Signature",
    shape: "Square",
    color: "Espresso",
    width: 144,
    size: "L",
    price: 2999,
    emoji: "👓",
  },
  {
    id: "f26",
    name: "Bloom",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Peach",
    width: 131,
    size: "S",
    price: 3299,
    emoji: "👓",
  },
  {
    id: "f27",
    name: "Drift",
    brand: "Gowri Air",
    shape: "Aviator",
    color: "Black Mirror",
    width: 146,
    size: "L",
    price: 3399,
    emoji: "🕶️",
  },
  {
    id: "f28",
    name: "Loft",
    brand: "Gowri Edge",
    shape: "Rectangle",
    color: "Walnut",
    width: 140,
    size: "M",
    price: 2499,
    emoji: "👓",
  },
  {
    id: "f29",
    name: "Halcyon",
    brand: "Gowri Signature",
    shape: "Round",
    color: "Champagne",
    width: 137,
    size: "M",
    price: 2899,
    emoji: "👓",
  },
  {
    id: "f30",
    name: "Volt",
    brand: "Gowri Edge",
    shape: "Square",
    color: "Electric Blue",
    width: 142,
    size: "M",
    price: 2799,
    emoji: "👓",
  },
  {
    id: "f31",
    name: "Wren",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Plum",
    width: 135,
    size: "M",
    price: 3099,
    emoji: "👓",
  },
  {
    id: "f32",
    name: "Cove",
    brand: "Gowri Signature",
    shape: "Round",
    color: "Sea Green",
    width: 130,
    size: "S",
    price: 2599,
    emoji: "👓",
  },
  {
    id: "f33",
    name: "Pinnacle",
    brand: "Gowri Air",
    shape: "Aviator",
    color: "Rose Mirror",
    width: 145,
    size: "L",
    price: 3699,
    emoji: "🕶️",
  },
  {
    id: "f34",
    name: "Marlowe",
    brand: "Gowri Edge",
    shape: "Rectangle",
    color: "Onyx",
    width: 148,
    size: "L",
    price: 2899,
    emoji: "👓",
  },
  {
    id: "f35",
    name: "Sable",
    brand: "Gowri Signature",
    shape: "Square",
    color: "Sand",
    width: 139,
    size: "M",
    price: 2399,
    emoji: "👓",
  },
  {
    id: "f36",
    name: "Wisp",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Ivory",
    width: 132,
    size: "S",
    price: 2999,
    emoji: "👓",
  },
  {
    id: "f37",
    name: "Onyx",
    brand: "Gowri Edge",
    shape: "Square",
    color: "Carbon",
    width: 143,
    size: "M",
    price: 3099,
    emoji: "👓",
  },
  {
    id: "f38",
    name: "Solace",
    brand: "Gowri Signature",
    shape: "Round",
    color: "Mocha",
    width: 141,
    size: "M",
    price: 2799,
    emoji: "👓",
  },
  {
    id: "f39",
    name: "Crest",
    brand: "Gowri Air",
    shape: "Aviator",
    color: "Matte Gold",
    width: 147,
    size: "L",
    price: 3499,
    emoji: "🕶️",
  },
  {
    id: "f40",
    name: "Verve",
    brand: "Gowri Edge",
    shape: "Rectangle",
    color: "Steel Blue",
    width: 138,
    size: "M",
    price: 2599,
    emoji: "👓",
  },
  {
    id: "f41",
    name: "Linnet",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Mint",
    width: 134,
    size: "S",
    price: 3199,
    emoji: "👓",
  },
  {
    id: "f42",
    name: "Maven",
    brand: "Gowri Signature",
    shape: "Square",
    color: "Cocoa",
    width: 145,
    size: "L",
    price: 2899,
    emoji: "👓",
  },
  {
    id: "f43",
    name: "Reef",
    brand: "Gowri Air",
    shape: "Aviator",
    color: "Teal Mirror",
    width: 146,
    size: "L",
    price: 3599,
    emoji: "🕶️",
  },
  {
    id: "f44",
    name: "Juno",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Wine",
    width: 136,
    size: "M",
    price: 3099,
    emoji: "👓",
  },
  {
    id: "f45",
    name: "Stark",
    brand: "Gowri Edge",
    shape: "Rectangle",
    color: "Graphite",
    width: 144,
    size: "L",
    price: 2499,
    emoji: "👓",
  },
  {
    id: "f46",
    name: "Lark",
    brand: "Gowri Signature",
    shape: "Round",
    color: "Soft Caramel",
    width: 133,
    size: "S",
    price: 2699,
    emoji: "👓",
  },
  {
    id: "f47",
    name: "Hollow",
    brand: "Gowri Edge",
    shape: "Square",
    color: "Midnight",
    width: 142,
    size: "M",
    price: 2999,
    emoji: "👓",
  },
  {
    id: "f48",
    name: "Selene",
    brand: "Gowri Bloom",
    shape: "Cat-Eye",
    color: "Pearl",
    width: 131,
    size: "S",
    price: 3399,
    emoji: "👓",
  },
  {
    id: "f49",
    name: "Orbit",
    brand: "Gowri Air",
    shape: "Aviator",
    color: "Copper",
    width: 149,
    size: "L",
    price: 3699,
    emoji: "🕶️",
  },
  {
    id: "f50",
    name: "Cedar",
    brand: "Gowri Signature",
    shape: "Rectangle",
    color: "Forest",
    width: 140,
    size: "M",
    price: 2599,
    emoji: "👓",
  },
];

export const POWER_OPTIONS = [
  "Zero Power (Blue Cut)",
  "Single Vision (-0.25 to -6.00)",
  "Single Vision (+0.25 to +4.00)",
  "Bifocal",
  "Progressive",
  "Reading (+1.00 to +3.50)",
];

export const SIZE_RANGES: Record<Frame["size"], { label: string; range: string }> = {
  S: { label: "Small", range: "126–134 mm" },
  M: { label: "Medium", range: "135–142 mm" },
  L: { label: "Large", range: "143–150 mm" },
};

export function recommendSize(faceWidthMm: number): Frame["size"] {
  if (faceWidthMm < 132) return "S";
  if (faceWidthMm < 145) return "M";
  return "L";
}
